name = "Kiera"
license = "MIT"
licenselink = "https://github.com/avianto/hugo-kiera/blob/master/LICENSE.md"
description = "Hugo Theme for creative and technical writing"
homepage = "http://github.com/avianto/hugo-kiera"
tags = ["blog","minimal","responsive"]
features = ["blog","disqus","google-analytics","font-awesome"]
min_version = "0.30.2"
Copyright = "Â© 2019 0xguid.  <a href=\"http://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>."


[author]
  name = "b. avianto"
  homepage = "http://avianto.com/"
