baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "techie guide.."
share = false
footnoteReturnLinkContents = "â†©"
[taxonomies]
  tag = "tags"
  category = "categories"
  languages = "languages"