baseURL = "https://adoring-euclid-0f6ef9.netlify.com/"
languageCode = "en-us"
title = "0xguid"
share = false
menu = "main"
meta = "false"
footnoteReturnLinkContents = "↩"
canonifyurls = true
summaryLength = 30
enableEmoji = true
[author]
    name = "Saleh"       #Author name
    github = "0xguid"     #Github username
copyright = "© 2019 0xguid."
