baseURL = "https://adoring-euclid-0f6ef9.netlify.com/"
languageCode = "en-us"
title = "0xguid"
share = false
menu = "main"
meta = "false"
footnoteReturnLinkContents = "↩"
canonifyurls = true
summaryLength = 30
enableEmoji = true
copyright = "© 2019 0xguid.  <a href=\"http://creativecommons.org/licenses/by/4.0/\">Some rights reserved</a>."
