baseURL = "https://dslash.xyz"
languageCode = "en-us"
title = "0xguid"
share = false
menu = "main"
meta = "false"
footnoteReturnLinkContents = "â†©"
canonifyurls = true
summaryLength = 30
enableEmoji = true
copyright = "Copyright &copy; 2019 - Saleh"
pygmentsCodeFences = true

tags = ["blog",]
features = ["blog", ]
min_version = 0.14
sidebar = false

[author]
    name = "Saleh"

[original]
    author =  "Saleh"
    homepage = "https://github.com/0xguid"
    repo = "https://github.com/0xguid"