baseURL = "https://adoring-euclid-0f6ef9.netlify.com/"
languageCode = "en-us"
title = "0xguid"
share = false
menu = "main"
meta = "false"
footnoteReturnLinkContents = "â†©"
canonifyurls = true
summaryLength = 30
enableEmoji = true
copyright = "Copyright &copy; 2019 - Saleh"
pygmentsCodeFences = true

[author]
    name = "Saleh"       #Author name
    github = "0xguid"     #Github username
