baseURL = "https://adoring-euclid-0f6ef9.netlify.com/"
languageCode = "en-us"
title = "Software Development Rambling"
share = false
menu = "main"
meta = "false"
footnoteReturnLinkContents = "â†©"
canonifyurls = true
summaryLength = 30
enableEmoji = true